import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";

import FeaturedPost from "../components/FeaturedPost";
import RecentPosts from "../components/RecentPosts";

import prisma from "../lib/prisma";

type PostType = {
  id: string;
  title: string;
  content: string;
  createdAt: string;
  updatedAt: string;
  images: [
    {
      id: string;
      url: string;
    }
  ];
};

type HomePageType = {
  posts: PostType[];
};

const Home: NextPage<HomePageType> = ({ posts }) => {
  console.log(posts);
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FeaturedPost
          id={posts[0].id}
          title={posts[0].title}
          body={posts[0].content}
          createdAt={posts[0].createdAt}
          updatedAt={posts[0].updatedAt}
          imgUrl={posts[0].images[0].url}
        />
        <RecentPosts posts={posts} />
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = await prisma.post.findMany({
    where: {
      published: true,
    },
    select: {
      id: true,
      title: true,
      content: true,
      createdAt: true,
      updatedAt: true,
      author: {
        select: {
          id: true,
          name: true,
          profilePicture: true,
        },
      },
      images: {
        select: {
          id: true,
          url: true,
        },
      },
    },
  });

  posts.forEach((post) => {
    // @ts-ignore
    post.createdAt = post.createdAt.toJSON();
    // @ts-ignore
    post.updatedAt = post.updatedAt.toJSON();
  });

  return { props: { posts } };
};

export default Home;
