import type { NextPage } from "next";
import Head from "next/head";

import FeaturedPost from "../components/FeaturedPost";
import RecentPosts from "../components/RecentPosts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FeaturedPost
          title="First blog post"
          body="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet, illum
          nisi. Ea itaque voluptatum aliquid commodi aut? Velit alias delectus
          dolore, quidem dignissimos fugiat! Maiores esse doloribus commodi odio
          in?"
          createdAt={new Date()}
          imgUrl="https://dummyimage.com/600x400/4b5563/ffffff&text=hello"
        />
        <RecentPosts />
      </main>
    </>
  );
};

export default Home;
