import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";

import FeaturedPost from "../components/FeaturedPost";
import RecentPosts from "../components/RecentPosts";

import prisma from "../lib/prisma";

import { PostType } from "../types";

type HomePageType = {
  posts: PostType[];
};

const Home: NextPage<HomePageType> = ({ posts }) => {
  if (posts.length < 1)
    return (
      <>
        <h1 className="text-3xl">Please stand by!</h1>
        <h2 className="text-xl mt-5">
          Our website is currently down. We&apos;re working on this.
        </h2>
      </>
    );

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FeaturedPost
          id={posts[0].id}
          title={posts[0].title}
          body={posts[0].content}
          createdAt={posts[0].createdAt}
          updatedAt={posts[0].updatedAt}
          imgUrl={posts[0].imageUrl}
        />
        <RecentPosts posts={posts} />
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = await prisma.post.findMany({
    where: {
      published: true,
      accepted: true,
    },
    select: {
      id: true,
      title: true,
      content: true,
      createdAt: true,
      updatedAt: true,
      imageUrl: true,
    },
  });

  console.log(posts);

  posts.forEach((post) => {
    // @ts-ignore
    post.createdAt = post.createdAt.toJSON();
    // @ts-ignore
    post.updatedAt = post.updatedAt.toJSON();
  });

  return { props: { posts }, revalidate: 1 };
};

export default Home;
